#!/bin/bash -x
#
# Run site.yml or one of the playbooks from plays/ dir
#
# Usage:
#
# Whole site:
# ./run
#
# Partial plays (any one of the following is supported):
#
# ./run gps
# ./run gps.yml
# ./run plays/gps.yml
#
# Additional parameters are passed to ansible-playbook:
#
# ./run gps --tags config


target="site.yml"

if [ $# -gt 0 ]; then
    play=$1

    for possible in "${play}" "plays/${play}" "plays/${play}.yml"; do
        if [ -f "${possible}" ]; then
            target="${possible}"
            shift
            break
        fi
    done
fi

ANSIBLE_CONFIG=config ansible-playbook -f 100 -v ${target} $*
